# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'traefik'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['10.0.0.1:4000']

  - job_name: 'haproxy'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['192.168.51.218']
    
  - job_name: 'epay-payments-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['20.0.0.1:9005']
    - targets: ['192.168.104.37:9005']
    - targets: ['192.168.104.37:9006']
    - targets: ['192.168.132.213:9005']
    - targets: ['192.168.132.213:9006']

