version: '3.5'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    ports:
      - '3306:3306'
    networks:
      local:
        aliases:
          - mysql.lo
    volumes:
      - '${MYSQL_DATA}:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:12.1.6-ce.0'
    ports:
      - '3080:80'
      - '3443:443'
      - '3022:22'
    networks:
      local:
        aliases:
          - gitlab.lo
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitlab"
      - "traefik.docker.network=local"
      - "traefik.frontend.rule=Host:gitlab.lo"
      - "traefik.port=80"
    volumes:
      - '${GITLAB_DATA}/configs:/etc/gitlab'
      - '${GITLAB_DATA}/logs:/var/log/gitlab'
      - '${GITLAB_DATA}/data:/var/opt/gitlab'

  registry:
    container_name: registry
    image: 'registry:2'
    ports:
      - '5000:5000'
    networks:
      local:
        aliases:
          - registry.lo
    volumes:
      - '${REGISTRY_DATA}/images:/var/lib/registry'
      - '${REGISTRY_DATA}/certs:/certs'

  gitlab-runner-1:
    container_name: gitlab-runner-1
    image: 'gitlab/gitlab-runner:v12.1.0'
    networks:
      local:
        aliases:
          - gitlab-runner-1.lo
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${PWD}/gitlab-runner-config.toml:/etc/gitlab-runner/config.toml'

  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.11.2'
    ports:
      - '9090:9090'
    networks:
      local:
        aliases:
          - prometheus.lo
    volumes:
      - '${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml'
      - '${PROMETHEUS_DATA}:/prometheus'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.docker.network=local"
      - "traefik.frontend.rule=Host:prometheus.lo"
      - "traefik.port=9090"

  grafana:
    container_name: grafana
    image: 'grafana/grafana:6.3.0'
    ports:
      - '3000:3000'
    networks:
      local:
        aliases:
          - grafana.lo
    volumes:
      - '${GRAFANA_DATA}:/var/lib/grafana'
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.docker.network=local"
      - "traefik.frontend.rule=Host:grafana.lo"
      - "traefik.port=3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

  traefik:
    container_name: traefik
    command: --loglevel=DEBUG
    image: traefik:v1.7
    restart: always
    ports:
      - "4000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik.toml:/traefik.toml
    networks:
      local:
        ipv4_address: 172.30.0.2

networks:
  local:
    external: true
     
    
