# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
    
  - job_name: 'scape-core'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['10.0.0.1:4000']

  - job_name: 'epay-ecocash-endpoint'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['192.168.51.213:8080']
    - targets: ['192.168.51.214:8080']

  - job_name: 'epay-core'
    scrape_interval: 2s
    metrics_path: '/epay/actuator/prometheus'
    static_configs:
    - targets: ['192.168.51.215:8003']
    - targets: ['192.168.51.216:8003']
    - targets: ['192.168.51.217:8003']

  - job_name: 'epay-recharge-provider'
    scrape_interval: 2s
    metrics_path: '/recharge-provider/actuator/prometheus'
    static_configs:
    - targets: ['10.0.0.1:9001']

  - job_name: 'epay-load-test'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['10.0.0.1:9009']

  - job_name: 'haexp-104-58'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['10.0.0.1:9101']