version: '2.2'
services:
  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.11.2'
    ports:
      - '9090:9090'
    networks:
      local:
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.lo`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    container_name: grafana
    image: 'grafana/grafana:7.1.3'
    ports:
      - '3023:3000'
    volumes:
      - './config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml'
    networks:
      local:
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.lo`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.enable=true"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: novatec-sdg-panel
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: novatec-sdg-panel

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.18.1
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      local:
    labels:
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.lo`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
    ports:
      - 9411:9411
      - 6831:6831
      - 16686:16686

networks:
  local:
    external: true
