## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}`)
# API and dashboard configuration
api:
  insecure: true
metrics:
  prometheus: {}
tracing:
  zipkin: {}
ping: {}
log:
  level: DEBUG