## traefik.yml
entryPoints:
  http:
    address: ":80"

  https:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}`)
# API and dashboard configuration
api:
  insecure: true
metrics:
  prometheus: {}
tracing:
  zipkin: 
    httpEndpoint: http://10.0.0.1:9411/api/v2/spans
ping: {}
log:
  level: DEBUG

#tls
tls:
  certificates:
    - certFile: /traefik.lo.pem
      keyFile: /traefik.lo-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /traefik.lo.pem
        keyFile: /traefik.lo-key.pem