version: '3.5'

networks:
  kafka:
    name: kafka
    driver: bridge

services:
  zookeeper:
    image: 'zookeeper:3.4.9'
    networks:
      - kafka
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafdrop:
    image: obsidiandynamics/kafdrop
    networks:
      - kafka
    labels:
      - "traefik.http.routers.kafdrop.rule=Host(`kafdrop.lo`)"
      - "traefik.http.services.kafdrop.loadbalancer.server.port=9000"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"
  kafka1:
    image: 'bitnami/kafka:2.6.0'
    networks:
      - kafka    
    ports:
      - '9092:9092'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:2.6.0'
    networks:
      - kafka    
    ports:
      - '9093:9092'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:2.6.0'
    networks:
      - kafka    
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper